development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
<<<<<<< HEAD
  channel_prefix: apiTesting_2_app_production
=======
  channel_prefix: itinaapi_production
>>>>>>> 4889905de938500d24e9cb26fffecede1ab62dd8
